<div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">General</li>
              <li><a href="https://github.com/">Github</a></li>
              <li><a href="http://stackoverflow.com/">Stackoverflow</a></li>
              <li class="nav-header">Free</li>
<!--               <li class="active"><a href="#">Link</a></li> -->
              <li><a href="http://www.codecademy.com">Codecademy</a></li>
              <li><a href="http://www.learnstreet.com">Learn Street</a></li>
              <li><a href="http://www.codeschool.com">Codeschool</a></li>
              <li><a href="http://teamtreehouse.com">Treehouse</a></li>
              <li><a href="http://www.coursera.org">Coursera</a></li>
              <li><a href="https://www.udacity.com">Udacity</a></li>
              <li><a href="https://www.udemy.com/courses/Technology?price=free">Udemy</a></li>
              <li><a href="http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/">MIT</a></li>
              <li><a href="http://docs.webplatform.org/wiki/Main_Page">Web Platform</a></li>
              <li><a href="https://p2pu.org/en/groups/schools/school-of-webcraft/">P2P2</a></li>
              <li><a href="http://www.programr.com">Programr</a></li>
              <li><a href="http://www.saylor.org/saylor-foundation-status/#Computer%20Science">Saylor</a></li>
              <li><a href="http://thecodeplayer.com">The Code Player</a></li>
              <li><a href="http://www.khanacademy.org/cs/tutorials/programming-basics">Khan Academy</a></li>
              <li><a href="http://www.html5rocks.com/en/tutorials/">HTML5 Rocks (JS,HTML,CSS+)</a></li>
              <li><a href="http://webdesign.tutsplus.com/category/tutorials/">Tuts+</a></li>
              <li><a href="http://css-tricks.com">CSS Tricks (CSS, HTML, JS, PHP)</a></li>
              <li><a href="http://www.dontfeartheinternet.com">Don't Fear the Internet</a></li>
              <li><a href="http://www.webmonkey.com/tutorials/">Web Monkey</a></li>
              <li><a href="http://www.codeavengers.com/">Code Avengers</a></li>
              <li class="nav-header">Paid</li>
              <li><a href="http://teamtreehouse.com">Treehouse</a></li>
              <li><a href="http://www.codeschool.com">Codeschool</a></li>
              <li><a href="http://www.lynda.com/18j">Lynda</a></li>
              <li><a href="https://www.udemy.com/courses/Technology">Udemy</a></li>
              <li><a href="https://tutsplus.com/">Tuts+Premium</a></li>
              <li><a href="https://learnable.com/home">Learnable</a></li>
              <li><a href="https://shop.smashingmagazine.com/workshops/">Smashing Magazine Workshops</a></li>
              <li><a href="https://generalassemb.ly">General Assembly</a></li>
              <li><a href="http://www.codeavengers.com/">Code Avengers</a></li>
<!--               <li class="nav-header">Discounts</li>
              <li><a href="#">Link</a></li> -->
              <li class="nav-header">Screencasts</li>
              <li><a href="http://devblog.avdi.org/2013/06/21/a-list-of-programming-screencast-series/">Devblog</a></li>
              <li><a href="http://readwrite.com/2008/05/28/15_places_to_find_great_screencasts#awesm=~o9ankBjUK164W0">ReadWrite list (older but good)</a></li>
              <li class="nav-header">Bootcamps</li>
              <li><a href="http://bootcamper.io/">Bootcamper</a></li>
              <li><a href="http://www.bootcamps.in/">Bootcamps.in</a></li>
<!--               <li class="nav-header">Events/Calendar</li>
              <li><a href="#">New York City</a></li>
              <li><a href="#">San Francisco</a></li>
              <li><a href="#">Portland, Oregon</a></li> -->
<!--               <li class="nav-header">Language Portal</li>
              <li><a href="#">HTML/CSS</a></li>
              <li><a href="#">JS</a></li>
              <li><a href="#">Ruby</a></li>
              <li><a href="#">Python</a></li>
              <li><a href="#">PHP</a></li>
              <li><a href="#">C++</a></li> -->
<!--               <li class="nav-header">Other Tools</li>
              <li><a href="#">Templates</a></li>
              <li><a href="#">Plugins</a></li>
              <li><a href="#">CMSs</a></li>
              <li><a href="#">Boilerplates</a></li>
              <li><a href="#">Hosting</a></li>
              <li><a href="#">Domains</a></li>
              <li><a href="#">Text Editors</a></li>
              <li><a href="#">Read Stuff</a></li> -->
            </ul>
          </div><!--/.well -->
        </div><!--/span-->